# Generated by Django 3.0.2 on 2020-01-06 21:10

from django.db import migrations, models
import tracker.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoodRecord",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.IntegerField(validators=[tracker.models.validate_score]),
                ),
                ("description", models.TextField(max_length=500)),
            ],
        ),
    ]
