# Generated by Django 3.0.2 on 2020-01-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_auto_20200106_2120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodrecord",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
